SELECT DDPOGLBAL_MISMATCH_BRANCH.*, MIG_DETAIL.MIG_END_DATE, MBRN.MBRN_NAME
    FROM DDPOGLBAL_MISMATCH_BRANCH, MBRN, MIG_DETAIL
   WHERE     DDPOGLBAL_MISMATCH_BRANCH.BRANCH_CODE = MBRN.MBRN_CODE
         AND MBRN.MBRN_CODE = MIG_DETAIL.BRANCH_CODE
         AND DDPOGLBAL_MISMATCH_BRANCH.CHECKING_DATE = '23-JAN-2016'
ORDER BY MIG_DETAIL.MIG_END_DATE DESC