SELECT TO_CHAR (:P_TRAN_DATE, 'DD-MM-YYYY') MISMATCH_DATE,
       :P_BRANCH_CODE BRANCH_CODE,
       AA.*,
       BB.*,
       NVL (AA.AMOUNT, 0) - NVL (BB.AMOUNT, 0) DIFF
  FROM (SELECT 'DDPOPAYDB' IDENTIFY,
               'C' DBCR,
               COUNT (*) TOTAL_NUMBER_OF_INST,
               NVL (SUM (DDPOPAYDB_INST_AMT), 0) AMOUNT
          FROM DDPOPAYDB
         WHERE     DDPOPAYDB_ENTITY_NUM = 1
               AND DDPOPAYDB_ISSUED_BANK = 200
               AND DDPOPAYDB_ADVICE_REC_DATE = :P_TRAN_DATE
               AND DDPOPAYDB_ISSUED_ON_BRN = :P_BRANCH_CODE
               AND DDPOPAYDB_REMIT_CODE IN ('2', '9')
        UNION ALL
        SELECT 'DDPOPAYDB' IDENTIFY,
               'D' DBCR,
               COUNT (*) TOTAL_NUMBER_OF_INST,
               NVL (SUM (DDPOPAYDB_INST_AMT), 0) AMOUNT FROM 
                (SELECT  *
                        FROM DDPOPAYDB
                        WHERE     DDPOPAYDB_ENTITY_NUM = 1
                            AND DDPOPAYDB_ISSUED_BANK = 200
                            AND DDPOPAYDB_ISSUED_ON_BRN = :P_BRANCH_CODE
                            AND DDPOPAYDB_PAY_CAN_DUP_DATE = :P_TRAN_DATE
                            AND DDPOPAYDB_REMIT_CODE IN ('2', '9')
                            AND DDPOPAYDB_STATUS NOT IN ('R', 'E')
                UNION ALL 
                SELECT  *
                        FROM DDPOPAYDB
                        WHERE     DDPOPAYDB_ENTITY_NUM = 1
                            AND DDPOPAYDB_ISSUED_BANK = 200
                            AND DDPOPAYDB_ISSUED_ON_BRN = :P_BRANCH_CODE
                            AND DDPOPAYDB_ADVICE_REC_DATE = :P_TRAN_DATE
                            AND DDPOPAYDB_REMIT_CODE IN ('2', '9')
                            AND DDPOPAYDB_STATUS IN ('R') )
                            ) AA
       LEFT OUTER JOIN
       (  SELECT 'TRAN' IDENTIFY,
                 TRAN_DB_CR_FLG DBCR,
                 COUNT (*) TOTAL_NUMBER_OF_INST,
                 SUM (TRAN_AMOUNT) AMOUNT
            FROM TRAN2015
           WHERE     TRAN_ENTITY_NUM = 1
                 AND TRAN_DATE_OF_TRAN = :P_TRAN_DATE
                 AND TRAN_ACING_BRN_CODE = :P_BRANCH_CODE
                 AND TRAN_GLACC_CODE = '134101101'
                 AND TRAN_AUTH_BY IS NOT NULL
                 AND TRAN_AMOUNT <> 0
        GROUP BY TRAN_DB_CR_FLG) BB
          ON (AA.DBCR = BB.DBCR);



SELECT DDPOPAY_REMIT_CODE, DDPOPAY_INST_PFX, DDPOPAY_INST_NUM, TRAN_AMOUNT
  FROM DDPOPAY , TRAN2016
 WHERE     DDPOPAY_ENTITY_NUM = 1
       AND DDPOPAY_BRN_CODE = :P_BRANCH_CODE
       AND DDPOPAY_PAY_DATE = :P_TRAN_DATE
       AND DDPOPAY_AUTH_ON IS NOT NULL
       AND DDPOPAY_REMIT_CODE IN ('2', '9')
       AND TRAN_ENTITY_NUM = 1
       AND TRAN_BATCH_NUMBER = POST_TRAN_BATCH_NUM
       AND TRAN_VALUE_DATE = :P_TRAN_DATE
       AND TRAN_ACING_BRN_CODE = :P_BRANCH_CODE
       AND TRAN_GLACC_CODE = '134101101'
       AND TRAN_DB_CR_FLG = 'D'
MINUS
SELECT DDPOPAYDB_REMIT_CODE, DDPOPAYDB_INST_PFX, DDPOPAYDB_LEAF_NUM, DDPOPAYDB_INST_AMT
  FROM DDPOPAYDB
 WHERE     DDPOPAYDB_ENTITY_NUM = 1
       AND DDPOPAYDB_ISSUED_BANK = 200
       AND DDPOPAYDB_ISSUED_ON_BRN = :P_BRANCH_CODE
       AND DDPOPAYDB_PAY_CAN_DUP_DATE = :P_TRAN_DATE
       AND DDPOPAYDB_REMIT_CODE IN ('2', '9');
       
       
       

SELECT DDPOPAYDB_REMIT_CODE, DDPOPAYDB_INST_PFX, DDPOPAYDB_LEAF_NUM, DDPOPAYDB_INST_AMT
  FROM DDPOPAYDB
 WHERE     DDPOPAYDB_ENTITY_NUM = 1
       AND DDPOPAYDB_ISSUED_BANK = 200
       AND DDPOPAYDB_ISSUED_ON_BRN = :P_BRANCH_CODE
       AND DDPOPAYDB_PAY_CAN_DUP_DATE = :P_TRAN_DATE
       AND DDPOPAYDB_REMIT_CODE IN ('2', '9')
MINUS
SELECT DDPOPAY_REMIT_CODE, DDPOPAY_INST_PFX, DDPOPAY_INST_NUM, TRAN_AMOUNT
  FROM DDPOPAY , TRAN2016
 WHERE     DDPOPAY_ENTITY_NUM = 1
       AND DDPOPAY_BRN_CODE = :P_BRANCH_CODE
       AND DDPOPAY_PAY_DATE = :P_TRAN_DATE
       AND DDPOPAY_AUTH_ON IS NOT NULL
       AND DDPOPAY_REMIT_CODE IN ('2', '9')
       AND TRAN_ENTITY_NUM = 1
       AND TRAN_BATCH_NUMBER = POST_TRAN_BATCH_NUM
       AND TRAN_VALUE_DATE = :P_TRAN_DATE
       AND TRAN_ACING_BRN_CODE = :P_BRANCH_CODE
       AND TRAN_GLACC_CODE = '134101101'
       AND TRAN_DB_CR_FLG = 'D'; 


SELECT *
  FROM TRAN2017
 WHERE     TRAN_ENTITY_NUM = 1
       AND TRAN_DATE_OF_TRAN = :P_TRAN_DATE
       AND TRAN_ACING_BRN_CODE = :P_BRANCH_CODE
       AND TRAN_GLACC_CODE = '134101101'
       AND TRAN_AUTH_BY IS NOT NULL
       AND TRAN_DB_CR_FLG = 'C';



SELECT DDADVPARTDTL_REM_CODE,
       DDADVPARTDTL_LEAF_PFX,
       DDADVPARTDTL_LEAF_NUMBER,
       DDADVPARTDTL_INST_AMT
  FROM DDADVPARTDTL
 WHERE     DDADVPARTDTL_ENTITY_NUM = 1
       AND DDADVPARTDTL_BRN_CODE = :P_BRANCH_CODE
       AND DDADVPARTDTL_ADV_REC_DATE = :P_TRAN_DATE
       AND DDADVPARTDTL_REM_CODE IN ('2', '9')
MINUS
SELECT DDPOPAYDB_REMIT_CODE,
       DDPOPAYDB_INST_PFX,
       DDPOPAYDB_LEAF_NUM,
       DDPOPAYDB_INST_AMT
  FROM DDPOPAYDB
 WHERE     DDPOPAYDB_ENTITY_NUM = 1
       AND DDPOPAYDB_ISSUED_BANK = 200
       AND DDPOPAYDB_ISSUED_ON_BRN = :P_BRANCH_CODE
       AND DDPOPAYDB_ADVICE_REC_DATE = :P_TRAN_DATE
       AND DDPOPAYDB_REMIT_CODE IN ('2', '9');