CREATE OR REPLACE FUNCTION FN_GET_BRN_CODE (P_ADMIN_CODE NUMBER, P_FLAG NUMBER , P_LIST_ID NUMBER )
   RETURN NUMBER
IS
   V_COUNT    NUMBER;
   V_RETURN   NUMBER;
BEGIN
   SELECT COUNT (*)
     INTO V_COUNT
     FROM MBRN
    WHERE MBRN_PARENT_ADMIN_CODE = P_ADMIN_CODE;
   IF V_COUNT = 0
   THEN
      DBMS_OUTPUT.PUT_LINE (P_ADMIN_CODE);
      INSERT INTO BRANCH_ADMIN (LIST_ID, BRANCH_CODE) VALUES (P_LIST_ID, P_ADMIN_CODE);
   ELSE
      BEGIN
         FOR IDX IN (SELECT *
                       FROM MBRN
                      WHERE MBRN_PARENT_ADMIN_CODE = P_ADMIN_CODE)
         LOOP
            V_RETURN := FN_GET_BRN_CODE (IDX.MBRN_CODE, 1, P_LIST_ID);
         END LOOP;
         IF P_FLAG = 1 THEN
            DBMS_OUTPUT.PUT_LINE (P_ADMIN_CODE);
            INSERT INTO BRANCH_ADMIN (LIST_ID, BRANCH_CODE) VALUES (P_LIST_ID, P_ADMIN_CODE);
         END IF ;
      END;
   END IF;

   RETURN 0;
END;





CREATE OR REPLACE PROCEDURE SP_BRANCH_ADMIN_GEN
IS
V_LIST_ID NUMBER ;
V_RETURN NUMBER ;
BEGIN
V_LIST_ID := 12 ;
   BEGIN
      FOR IDX
         IN (  SELECT DISTINCT MBRN_PARENT_ADMIN_CODE
                 FROM MBRN M
                WHERE     MBRN_PARENT_ADMIN_CODE NOT IN (0, 18)
                      AND M.MBRN_CODE IN (SELECT BRANCH_CODE FROM MIG_DETAIL)
             ORDER BY MBRN_PARENT_ADMIN_CODE)
      LOOP
         V_RETURN := FN_GET_BRN_CODE(IDX.MBRN_PARENT_ADMIN_CODE, 0, V_LIST_ID );
         
         UPDATE BRANCH_ADMIN SET ADMIN_CODE = IDX.MBRN_PARENT_ADMIN_CODE WHERE LIST_ID = V_LIST_ID ;
         
         V_LIST_ID := V_LIST_ID + 1 ;
      END LOOP;
   END;
END;




INSERT INTO BRNLIST
    SELECT  1 BRNLIST_ENTITY_NUM,
        LIST_ID  BRNLIST_LIST_NUM,
       BRN_NAME BRNLIST_LIST_DESCN,
       'INTELECT' BRNLIST_ENTD_BY,
       SYSDATE BRNLIST_ENTD_ON,
       NULL BRNLIST_LAST_MOD_BY,
       NULL BRNLIST_LAST_MOD_ON,
       'INTELECT' BRNLIST_AUTH_BY,
       SYSDATE BRNLIST_AUTH_ON,
       NULL TBA_MAIN_KEY FROM (
  SELECT DISTINCT LIST_ID, ADMIN_CODE, ( SELECT MM.MBRN_NAME FROM MBRN MM WHERE  MM.MBRN_CODE = ADMIN_CODE ) BRN_NAME
  FROM BRANCH_ADMIN ORDER BY ADMIN_CODE) ;
  
  
  
INSERT INTO BRNLISTDTL
  SELECT 1 BRNLISTDTL_ENTITY_NUM,
         LIST_ID BRNLISTDTL_LIST_NUM,
         ROW_NUMBER() OVER (PARTITION BY ADMIN_CODE ORDER BY ADMIN_CODE) BRNLISTDTL_DTL_SL,
         BRANCH_CODE BRNLISTDTL_BRN_CODE
    FROM BRANCH_ADMIN
ORDER BY 1;