ALTER TABLE
   RTMPLNIA
RENAME TO
   LOANIADLY; 
   
CREATE OR REPLACE SYNONYM RTMPLNIA FOR LOANIADLY ; 



ALTER TABLE LOANIADLY
 ADD (RTMPLNIA_INSERT_FROM  VARCHAR2(1 BYTE));


ALTER TABLE LOANIADLY
 ADD (RTMPLNIA_BRN_CODE  NUMBER(5));
 
 
 CREATE TABLE LOANIADLY_PART
(
  RTMPLNIA_RUN_NUMBER        NUMBER(6)          NOT NULL,
  RTMPLNIA_ACNT_NUM          NUMBER(14)         NOT NULL,
  RTMPLNIA_VALUE_DATE        DATE               NOT NULL,
  RTMPLNIA_ACCRUAL_DATE      DATE               NOT NULL,
  RTMPLNIA_ACNT_CURR         VARCHAR2(3 BYTE),
  RTMPLNIA_ACNT_BAL          NUMBER(18,3)       DEFAULT 0,
  RTMPLNIA_INT_ON_AMT        NUMBER(18,3)       DEFAULT 0,
  RTMPLNIA_OD_PORTION        NUMBER(18,3)       DEFAULT 0,
  RTMPLNIA_INT_RATE          NUMBER(8,5)        DEFAULT 0,
  RTMPLNIA_SLAB_AMT          NUMBER(18,3)       DEFAULT 0,
  RTMPLNIA_OD_INT_RATE       NUMBER(8,5)        DEFAULT 0,
  RTMPLNIA_LIMIT             NUMBER(18,3)       DEFAULT 0,
  RTMPLNIA_DP                NUMBER(18,3)       DEFAULT 0,
  RTMPLNIA_INT_AMT           NUMBER(18,9)       DEFAULT 0,
  RTMPLNIA_INT_AMT_RND       NUMBER(18,3)       DEFAULT 0,
  RTMPLNIA_OD_INT_AMT        NUMBER(18,9)       DEFAULT 0,
  RTMPLNIA_OD_INT_AMT_RND    NUMBER(18,3)       DEFAULT 0,
  RTMPLNIA_NPA_STATUS        NUMBER(1)          DEFAULT 0,
  RTMPLNIA_NPA_AMT           NUMBER(18,3)       DEFAULT 0,
  RTMPLNIA_ARR_OD_INT_AMT    NUMBER(18,3),
  RTMPLNIA_MAX_ACCRUAL_DATE  DATE               DEFAULT NULL,
  RTMPLNIA_INSERT_FROM       VARCHAR2(1 BYTE),
  RTMPLNIA_BRN_CODE          NUMBER(5)
)
partition by range (RTMPLNIA_BRN_CODE)
interval (1)
 store in (DATA, TBFES)
 ( partition p_NULL_PART values
 less than (1));


ALTER TABLE LOANIADLY_PART ADD (
  PRIMARY KEY
  (RTMPLNIA_RUN_NUMBER, RTMPLNIA_ACNT_NUM, RTMPLNIA_VALUE_DATE, RTMPLNIA_ACCRUAL_DATE)
  USING INDEX
    TABLESPACE CBSINDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);

  
CREATE INDEX IND_LOANIADLY ON LOANIADLY_PART(RTMPLNIA_BRN_CODE, RTMPLNIA_ACNT_NUM, RTMPLNIA_INSERT_FROM);
  
INSERT /*+ APPEND*/ INTO LOANIADLY_PART SELECT /*+ PARALLEL(64)*/* FROM LOANIADLY ;
  
DROP TABLE LOANIADLY ;

ALTER TABLE
   LOANIADLY_PART
RENAME TO
   LOANIADLY;