CREATE TABLE AML_RELATEDPARTY
(
  RELATED_PARTY_TYPE  VARCHAR2(35 BYTE),
  SALUTATION          VARCHAR2(15 BYTE),
  FIRST_NAME          VARCHAR2(100 BYTE),
  LAST_NAME           VARCHAR2(24 BYTE),
  FATHER_NAME         VARCHAR2(50 BYTE),
  MOTHER_NAME         VARCHAR2(50 BYTE),
  CREATION_DATE       DATE,
  DOB                 DATE,
  BIRTH_PLACE         VARCHAR2(50 BYTE),
  GENDER              VARCHAR2(6 BYTE),
  ID_TYPE             VARCHAR2(1000 BYTE),
  ID_VALUE            VARCHAR2(4000 BYTE),
  ISSUE_COUNTRY       VARCHAR2(4000 BYTE),
  ADDRESSTYPE         VARCHAR2(7 BYTE),
  PRESENTADDRESS      VARCHAR2(4000 BYTE),
  PRESENT_CITY        VARCHAR2(50 BYTE),
  PRESENT_COUNTRY     VARCHAR2(50 BYTE),
  PERMANENT_ADDRESS   VARCHAR2(4000 BYTE),
  PERMANENT_CITY      VARCHAR2(50 BYTE),
  PERMANENT_COUNTRY   VARCHAR2(50 BYTE),
  NATIONALITY         VARCHAR2(50 BYTE),
  RESIDENCE           VARCHAR2(4000 BYTE),
  OCCUPATION          VARCHAR2(50 BYTE),
  PHONE               VARCHAR2(30 BYTE),
  MOBILE              VARCHAR2(15 BYTE),
  IS_SIGNATORY        VARCHAR2(1 BYTE),
  EMAIL               VARCHAR2(4000 BYTE),
  ACCOUNT_NUMBER      VARCHAR2(30 BYTE),
  CUSTOMERNUMBER      NUMBER(12)
)
TABLESPACE TBFES
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;