SELECT * FROM DDPOGLBAL_MISMATCH_BRANCH WHERE BRANCH_CODE IN 
(SELECT BRANCH_CODE
 FROM DDPOGLBAL_MISMATCH_BRANCH
WHERE CHECKING_DATE = TRUNC(SYSDATE)
MINUS
SELECT BRANCH_CODE
 FROM DDPOGLBAL_MISMATCH_BRANCH
WHERE CHECKING_DATE ='19-apr-2016')
         AND CHECKING_DATE =TRUNC(SYSDATE)
