SELECT 'DD_INST' INEN, SUM(DD.DDPOPAYDB_INST_AMT)
 FROM DDPOPAYDB DD,
      (SELECT DDPOPAYDB_ENTITY_NUM,
              TO_NUMBER (DDPOPAYDB_ISSUED_ON_BRN) DDPOPAYDB_ISSUED_ON_BRN,
              DDPOPAYDB_REMIT_CODE,
              DDPOPAYDB_INST_PFX,
              DDPOPAYDB_LEAF_NUM,
              DDPOPAYDB_INST_AMT
         FROM DDPOPAYDB
        WHERE     DDPOPAYDB_ENTITY_NUM = 1
              AND DDPOPAYDB_REMIT_CODE  IN ('2','9')
              AND DDPOPAYDB_ISSUED_ON_BRN = :P_BRANCH_CODE
              AND NVL (DDPOPAYDB_STATUS, '#') NOT IN  ('C','D', 'R', 'E','L')
              AND DDPOPAYDB_ADVICE_REC_DATE <= TRUNC(SYSDATE) - 1
       MINUS
       SELECT DDPOPAY_ENTITY_NUM,
              DDPOPAY_BRN_CODE,
              DDPOPAY_REMIT_CODE,
              DDPOPAY_INST_PFX,
              DDPOPAY_INST_NUM,
              DDPOPAY_INST_AMT
         FROM DDPOPAY A, DDPOPAYDB B
        WHERE     A.DDPOPAY_INST_NUM = B.DDPOPAYDB_LEAF_NUM
              AND A.DDPOPAY_INST_PFX = B.DDPOPAYDB_INST_PFX
              AND A.DDPOPAY_REMIT_CODE = B.DDPOPAYDB_REMIT_CODE
              AND DDPOPAY_REMIT_CODE IN ('2','9')
              AND DDPOPAYDB_ISSUED_ON_BRN = :P_BRANCH_CODE
              AND DDPOPAY_BRN_CODE = :P_BRANCH_CODE
              AND NVL (DDPOPAYDB_STATUS, '#') NOT IN  ('C','D', 'R', 'E','L')
              AND DDPOPAY_REJ_ON IS NULL
              AND DDPOPAY_PAY_DATE <= TRUNC(SYSDATE) - 1) OUTS
WHERE     OUTS.DDPOPAYDB_ENTITY_NUM = DD.DDPOPAYDB_ENTITY_NUM
      AND OUTS.DDPOPAYDB_REMIT_CODE = DD.DDPOPAYDB_REMIT_CODE
      AND OUTS.DDPOPAYDB_INST_PFX = DD.DDPOPAYDB_INST_PFX
      AND OUTS.DDPOPAYDB_LEAF_NUM = DD.DDPOPAYDB_LEAF_NUM
      AND OUTS.DDPOPAYDB_ISSUED_ON_BRN = DD.DDPOPAYDB_ISSUED_ON_BRN     
      UNION ALL        
SELECT 'DD_GL' INEN,  GLBALH_BC_BAL FROM GLBALASONHIST
WHERE 
GLBALH_ENTITY_NUM = 1 AND  GLBALH_GLACC_CODE  = '134101101' AND  GLBALH_BRN_CODE = :P_BRANCH_CODE
AND GLBALH_ASON_DATE =  TRUNC(SYSDATE) - 1
