SELECT TO_NUMBER (DDPOPAYDB_ISSUED_ON_BRN),
         DDPOCAN_REMIT_CODE,
         DDPOCAN_LEAF_PFX,
         DDPOCAN_LEAF_NUMBER,
         DDPOCAN_BRN_CODE,
         DDPOCAN_CANC_DATE,
         DDPOCAN.POST_TRAN_BATCH_NUM
    FROM DDPOPAYDB, DDPOCAN, MIG_DETAIL
   WHERE     DDPOPAYDB_ADVICE_REC_DATE IS NULL
         AND DDPOPAYDB_STATUS = 'C'
         AND DDPOPAYDB_REMIT_CODE IN ('2', '9')
         AND DDPOPAYDB_REMIT_CODE = DDPOCAN_REMIT_CODE
         AND DDPOPAYDB_INST_PFX = DDPOCAN_LEAF_PFX
         AND DDPOPAYDB_LEAF_NUM = DDPOCAN_LEAF_NUMBER
         AND DDPOCAN_AUTH_BY IS NOT NULL
         AND TO_NUMBER (DDPOPAYDB_ISSUED_ON_BRN) IN
                (SELECT BRANCH_CODE FROM MIG_DETAIL)
         AND BRANCH_CODE = TO_NUMBER (DDPOPAYDB_ISSUED_ON_BRN)
         AND DDPOCAN_CANC_DATE >= MIG_END_DATE
ORDER BY TO_NUMBER (DDPOPAYDB_ISSUED_ON_BRN),
         DDPOCAN_REMIT_CODE,
         DDPOCAN_LEAF_PFX,
         DDPOCAN_LEAF_NUMBER,
         DDPOCAN_BRN_CODE,
         DDPOCAN_CANC_DATE,
         DDPOCAN.POST_TRAN_BATCH_NUM;
