CREATE OR REPLACE PROCEDURE SP_GEN_AML_FULLDATA_THREAD AS
  LN_DUMMY NUMBER;
BEGIN
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_FULLDATA(1,50); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_FULLDATA(51,100); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_FULLDATA(101,150); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_FULLDATA(151,200); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_FULLDATA(201,250); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_FULLDATA(251,300); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_FULLDATA(301,350); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_FULLDATA(351,400); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_FULLDATA(401,450); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_FULLDATA(451,500); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_FULLDATA(501,550); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_FULLDATA(551,600); end;',instance=>1);
  DBMS_JOB.SUBMIT(LN_DUMMY, 'begin SP_GEN_AML_FULLDATA(601,700); end;',instance=>1); 
  COMMIT;
END SP_GEN_AML_FULLDATA_THREAD;
/
