CREATE OR REPLACE FUNCTION FN_GET_PP_ISSUE_EXP_DATE (P_CLIENT_CODE NUMBER, P_DATE_FLAG VARCHAR)
   RETURN VARCHAR2
IS
   V_ISSUE_DATE  DATE;
   V_EXPIRY_DATE DATE ;
BEGIN
   BEGIN
      SELECT PIDDOCS_ISSUE_DATE, PIDDOCS_EXP_DATE
        INTO V_ISSUE_DATE, V_EXPIRY_DATE
        FROM PIDDOCS P
       WHERE     P.PIDDOCS_SOURCE_KEY = TO_CHAR (P_CLIENT_CODE)
             AND P.PIDDOCS_PID_TYPE = 'PP';
   EXCEPTION
      WHEN OTHERS
      THEN
         V_ISSUE_DATE := NULL;
         V_EXPIRY_DATE := NULL ;
   END;
    IF P_DATE_FLAG = 'I' THEN 
        RETURN V_ISSUE_DATE ;
    ELSE
        RETURN V_EXPIRY_DATE ;
    END IF ;
   
END FN_GET_PP_ISSUE_EXP_DATE;
/
