CREATE OR REPLACE FUNCTION FN_GET_PP_CNTRY (P_CLIENT_CODE NUMBER)
   RETURN VARCHAR2
IS
   V_CNTRY_CODE   VARCHAR2 (1000);
BEGIN
   BEGIN
      SELECT TO_CHAR (WM_CONCAT (TRIM (PIDDOCS_ISSUE_CNTRY)))
        INTO V_CNTRY_CODE
        FROM PIDDOCS P
       WHERE     P.PIDDOCS_SOURCE_KEY = TO_CHAR (P_CLIENT_CODE)
             AND P.PIDDOCS_PID_TYPE = 'PP';
   EXCEPTION
      WHEN OTHERS
      THEN
         V_CNTRY_CODE := NULL;
   END;

   RETURN V_CNTRY_CODE;
END FN_GET_PP_CNTRY;
/
