DROP INDEX IND_ACNTS_BRN_CODE_AC_TYPE ;


CREATE INDEX IND_ACNTS_BRN_CODE_AC_TYPE ON ACNTS
(ACNTS_ENTITY_NUM, ACNTS_BRN_CODE, ACNTS_AC_TYPE)
LOGGING
TABLESPACE TBFES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX IND_ACNTS_BRN_CODE_AC_TYPE ON ACNTS
(ACNTS_ENTITY_NUM, ACNTS_BRN_CODE, ACNTS_PROD_CODE, ACNTS_AC_TYPE)
LOGGING
TABLESPACE TBFES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;



UPDATE ACNTS SET ACNTS_INOP_ACNT = '0' , ACNTS_DORMANT_ACNT = '0' WHERE ACNTS_ENTITY_NUM = 1 AND ACNTS_INTERNAL_ACNUM IN (
SELECT ACNTSTATUS_INTERNAL_ACNUM FROM ACNTSTATUS  WHERE ACNTSTATUS_ENTITY_NUM = 1 AND ACNTSTATUS_EFF_DATE = '31-DEC-2019');


DELETE FROM ACNTSTATUS  WHERE ACNTSTATUS_ENTITY_NUM = 1 AND ACNTSTATUS_EFF_DATE = '31-DEC-2019' ;

DELETE FROM EODSODPROCBRN WHERE EODSODPROCBRN_ENTITY_NUM = 1 AND PROC_TYPE = 'E' AND PROC_NAME = 'PKG_DORINOPMARK.START_BRNWISE' AND PROC_DATE = '31-DEC-2019' ;


SELECT COUNT(*) FROM EODSODPROCBRN WHERE EODSODPROCBRN_ENTITY_NUM = 1 AND PROC_TYPE = 'E' AND PROC_NAME = 'PKG_DORINOPMARK.START_BRNWISE' AND PROC_DATE = '31-DEC-2019' ;

/*
SELECT PROC_DATE, COUNT(*) FROM EODSODPROCBRN WHERE EODSODPROCBRN_ENTITY_NUM = 1 AND PROC_TYPE = 'E'  AND PROC_DATE <= '31-JAN-2020'
GROUP BY 
PROC_DATE 
ORDER BY PROC_DATE DESC ;
*/