#### F12 and F42 Data Preparation
ORACLE_HOSTNAME=DRUATDB1; export ORACLE_HOSTNAME
ORACLE_UNQNAME=ORTBDB; export ORACLE_UNQNAME
ORA_CRS_HOME=/u01/app/11.2.0/grid;export ORA_CRS_HOME
ORACLE_BASE=/u01/app/oracle;export ORACLE_BASE
ORACLE_HOME=$ORACLE_BASE/product/11.2.0/db_1;export ORACLE_HOME
ORACLE_SID=ORTBDB; export ORACLE_SID
ORACLE_TERM=xterm; export ORACLE_TERM
PATH=/usr/sbin:$PATH; export PATH
PATH=$ORACLE_HOME/bin:$ORACLE_HOME/OPatch:$ORA_CRS_HOME/bin:$PATH; export PATH

LD_LIBRARY_PATH=$ORACLE_HOME/lib; export LD_LIBRARY_PATH
LIBPATH=$LD_LIBRARY_PATH; export LD_LIBRARY_PATH

sqlplus SBL180918/SBL180918 << FIN

BEGIN
SP_GEN_F12_F42_THREAD;
END;
/
