SELECT --DDPOPAYDB_INST_PFX, DDPOPAYDB_LEAF_NUM , DDPOPAYDB_INST_AMT
COUNT(*) NUMBER_OF_PO, NVL(SUM(DDD.DDPOPAYDB_INST_AMT), 0) PO_BALANCE
--DDPOPAYDB_LEAF_NUM
  FROM DDPOPAYDB DDD
 WHERE (DDD.DDPOPAYDB_INST_PFX, DDD.DDPOPAYDB_LEAF_NUM,
        DDD.DDPOPAYDB_INST_AMT) IN
       (SELECT DD.DDPOISSDTL_INST_NUM_PFX,
               DD.DDPOISSDTL_INST_NUM,
               DD.DDPOISSDTL_INST_AMT
          FROM DDPOISSDTL DD
         WHERE (DD.DDPOISSDTL_BRN_CODE, DD.DDPOISSDTL_REMIT_CODE,
                DD.DDPOISSDTL_ISSUE_DATE, DD.DDPOISSDTL_DAY_SL) IN
               (SELECT D.DDPOISS_BRN_CODE,
                       D.DDPOISS_REMIT_CODE,
                       D.DDPOISS_ISSUE_DATE,
                       D.DDPOISS_DAY_SL
                  FROM DDPOISS D
                 WHERE D.DDPOISS_ENTD_BY = 'MIG'))
   AND DDD.DDPOPAYDB_ISSUED_ON_BRN = :P_BRANCH_CODE
   AND DDD.DDPOPAYDB_REMIT_CODE = '1' ;
   
   
   
   SELECT 9494991 - 9383961 FROM DUAL ;