UPDATE EODSODPROCDTL
   SET ESPROCDTL_PROCESS_NAME = 'PKG_DORINOPMARK.START_BRNWISE'
 WHERE     ESPROCDTL_ENTITY_NUM = 1
       AND ESPROCDTL_RUN_STAGE = 'E'
       AND ESPROCDTL_DISABLED = '0'
       AND ESPROCDTL_PROCESS_NAME = 'PKG_DORINOPMARK.SP_DORINOPMARK';
	   
commit ;
