WITH PO_DATA
     AS (SELECT DDPOPAYDB_ENTITY_NUM,
                DDPOPAYDB_REMIT_CODE,
                DDPOPAYDB_INST_PFX,
                DDPOPAYDB_LEAF_NUM,
                DDPOPAYDB_ISSUED_BRN,
                DDPOPAYDB_INST_AMT,
                DDPOPAYDB_ISSUED_ON_BRN,
                DDPOPAYDB_BENEF_NAME1,
                DDPOPAYDB_STATUS,
                DDPOPAYDB_INST_DATE,
                DDPOPAYDB_PAY_CAN_DUP_DATE
           FROM DDPOPAYDB
          WHERE     DDPOPAYDB_ENTITY_NUM = 1
                AND DDPOPAYDB_REMIT_CODE = '1'
                AND DDPOPAYDB_ISSUED_BRN = :P_BRANCH_CODE
                --AND NVL(DDPOPAYDB_STATUS,'#') NOT IN ('C')
                AND DDPOPAYDB_ISSUED_ON_BRN = :P_BRANCH_CODE),
     DAY_WISE_DD_PO
     AS (  SELECT DDPOPAYDB_INST_DATE DDPOPAYDB_ADVICE_REC_DATE,
                  SUM (NVL (DDPOPAYDB_INST_AMT, 0)) CREDIT,
                  0 DEBIT,
                  COUNT (*) NUMBER_OF_INSTRUMENT_RECIVE,
                  0 NUMBER_OF_INSTRUMENT_PAY
             FROM PO_DATA
         GROUP BY DDPOPAYDB_INST_DATE
         UNION ALL
           SELECT DDPOPAYDB_PAY_CAN_DUP_DATE DDPOPAYDB_ADVICE_REC_DATE,
                  0 CREDIT,
                  SUM (NVL (DDPOPAYDB_INST_AMT, 0)) DEBIT,
                  0 NUMBER_OF_INSTRUMENT_RECIVE,
                  COUNT (*) NUMBER_OF_INSTRUMENT_PAY
             FROM PO_DATA
            WHERE NVL (DDPOPAYDB_STATUS, '#') IN ('P', 'C')
         GROUP BY DDPOPAYDB_PAY_CAN_DUP_DATE),
     DAY_WISE_DD_PO_BALANCE
     AS (SELECT '134104101' TRAN_GLACC_CODE,
                DDPOPAYDB_ADVICE_REC_DATE,
                DEBIT,
                CREDIT,
                SERIAL,
                SUM (CREDIT - DEBIT) OVER (ORDER BY SERIAL) BALANCE,
                ROW_NUMBER ()
                OVER (
                   PARTITION BY DDPOPAYDB_ADVICE_REC_DATE
                   ORDER BY DDPOPAYDB_ADVICE_REC_DATE, SERIAL DESC NULLS LAST)
                   SERIAL_DAY
           FROM (SELECT DDPOPAYDB_ADVICE_REC_DATE,
                        DEBIT,
                        CREDIT,
                        ROW_NUMBER ()
                        OVER (ORDER BY DDPOPAYDB_ADVICE_REC_DATE NULLS LAST)
                           SERIAL,
                        SUM (
                           CREDIT - DEBIT)
                        OVER (PARTITION BY DDPOPAYDB_ADVICE_REC_DATE
                              ORDER BY DDPOPAYDB_ADVICE_REC_DATE)
                           BALANCE
                   FROM DAY_WISE_DD_PO))
                   SELECT * FROM DAY_WISE_DD_PO_BALANCE ;
				   
				   
				   
				   
SELECT WRONGLY_PAID_PO.ISSUE_BRNACH , SUM(WRONGLY_PAID_PO.BALANCE) PAID_BALANCE, COUNT(*) TOTAL_NUMBER_OF_PO  FROM 
(SELECT DDPOPAYDB.DDPOPAYDB_ISSUED_BRN ISSUE_BRNACH,
       DDPOPAY.DDPOPAY_BRN_CODE PAY_BRANCH,
       DDPOPAYDB.DDPOPAYDB_REMIT_CODE ,
       DDPOPAYDB.DDPOPAYDB_INST_PFX,
       DDPOPAYDB.DDPOPAYDB_LEAF_NUM,
       DDPOPAYDB.DDPOPAYDB_INST_AMT BALANCE,
       DDPOPAY.DDPOPAY_PAY_DATE PAID_DATE,
       DDPOPAY.POST_TRAN_BATCH_NUM PAID_BATCH
  FROM DDPOPAY, DDPOPAYDB
 WHERE     DDPOPAY_ENTITY_NUM = DDPOPAYDB_ENTITY_NUM
       AND DDPOPAY_BRN_CODE <> DDPOPAYDB_ISSUED_BRN
       AND DDPOPAY_REMIT_CODE = DDPOPAYDB_REMIT_CODE
       AND DDPOPAY_INST_PFX = DDPOPAYDB_INST_PFX
       AND DDPOPAY_INST_NUM = DDPOPAYDB_LEAF_NUM
       AND DDPOPAY_ENTITY_NUM = 1
       AND DDPOPAYDB.DDPOPAYDB_REMIT_CODE = '1') WRONGLY_PAID_PO
       GROUP BY WRONGLY_PAID_PO.ISSUE_BRNACH
       ORDER BY 1;
	   
	   
	   
SELECT DDPOPAYDB.DDPOPAYDB_ISSUED_BRN ISSUE_BRNACH,
       DDPOPAY.DDPOPAY_BRN_CODE PAY_BRANCH,
       DDPOPAYDB.DDPOPAYDB_REMIT_CODE ,
       DDPOPAYDB.DDPOPAYDB_INST_PFX,
       DDPOPAYDB.DDPOPAYDB_LEAF_NUM,
       DDPOPAYDB.DDPOPAYDB_INST_AMT BALANCE,
       DDPOPAY.DDPOPAY_PAY_DATE PAID_DATE,
       DDPOPAY.POST_TRAN_BATCH_NUM PAID_BATCH
  FROM DDPOPAY, DDPOPAYDB
 WHERE     DDPOPAY_ENTITY_NUM = DDPOPAYDB_ENTITY_NUM
       AND DDPOPAY_BRN_CODE <> DDPOPAYDB_ISSUED_BRN
       AND DDPOPAY_REMIT_CODE = DDPOPAYDB_REMIT_CODE
       AND DDPOPAY_INST_PFX = DDPOPAYDB_INST_PFX
       AND DDPOPAY_INST_NUM = DDPOPAYDB_LEAF_NUM
       AND DDPOPAY_ENTITY_NUM = 1
       AND DDPOPAYDB.DDPOPAYDB_REMIT_CODE = '1'